### ISSUE TITLE
Please make sure you have `sentencepiece` installed in order to use this tokenizer.

### ISSUE THREAD

**Issue by robinvandernoord** [gsarti/ik-nlp-tutorials#2]
In the block about generative models and translation from Russian to English, running the following code gave an error:

```python
identifier = "Helsinki-NLP/opus-mt-ru-en"
tokenizer = AutoTokenizer.from_pretrained(identifier)

# -> ValueError: This tokenizer cannot be instantiated. Please make sure you have `sentencepiece` installed in order to use this tokenizer.

```

This can be solved by installing the following:
```jupyter
!pip install sentencepiece transformers[sentencepiece]
```

And afterwards restarting the runtime.

**Comment by gsarti** [comment]
Thank you! I will include `sentencepiece` as a dependency on the top of all the notebooks.
